# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: black-clothes

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DARK_SKY_API_KEY: ${env:DARK_SKY_API_KEY}

# The `functions` block defines what code to deploy
functions:
  getWeather:
    handler: handler.main
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: weather
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                lat: true
                lng: true
